### ISSUE TITLE
Dark theme: radial menu font not readable

### ISSUE THREAD

**Issue by mr-manuel** [node-red-contrib-themes/theme-collection#239]
### Describe the problem

If you apply the dark theme and open the radial menu the font is not readable.

![grafik](https://user-images.githubusercontent.com/12592765/209961594-46e1d2f1-8304-40d3-8c21-3ef188963603.png)

### Steps To Reproduce

Apply dark theme, then touch and hold on a node.

### Expected Behavior

It should look like this:

![grafik](https://user-images.githubusercontent.com/12592765/209961802-b5cc6db9-7606-4a9e-b21f-ee8660b2285f.png)

As a workaround I added this lines to `node-red-contrib-themes/theme-collection/themes/dark)/dark.min.css`

```css
.red-ui-editor-radial-menu-opt {
  color: var(--red-ui-primary-text-color)
}

.red-ui-editor-radial-menu-opt.red-ui-editor-radial-menu-opt-disabled {
  color: var(--red-ui-tertiary-border-color)
}
```

To solve the main problem in the Node-RED `style.min.css` the color should be added to the `red-ui-editor-radial-menu-opt ` class.

### Theme Collection version

3.0.6

### Node-RED version

3.0.2
